# Generated by Django 2.0.5 on 2018-05-24 16:36

from django.db import migrations
import uuid
from django.conf import settings


def bd_create(apps, schema_editor):

    Task = apps.get_model("taskTracker", "Tasks")
    db_alias=schema_editor.connection.alias
    Task_list=[]
    for i in range(5):
        Task_list.append(Task(key=str(uuid.uuid4()), name='task'+str(i), status='ADD', parent_id=None, user_id=None))

    Task.objects.using(db_alias).bulk_create(Task_list)

    Person = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias
    User_list = []
    for i in range(5):
        User_list.append(Person(first_name='name' + str(i), last_name='lastname' + str(i), username='user' + str(i)))
    Person.objects.using(db_alias).bulk_create(User_list)



class Migration(migrations.Migration):

    dependencies = [
        ('taskTracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bd_create),
    ]
