# Generated by Django 2.0.5 on 2018-05-23 07:44

from django.db import migrations
from django.contrib.auth.models import User
import uuid
from django.conf import settings

def combine_names(apps, schema_editor):

    Person = apps.get_model(settings.AUTH_USER_MODEL)
    db_alias = schema_editor.connection.alias
    User_list = []
    for i in range(5):
        User_list.append(Person(first_name='name'+str(i),last_name='lastname'+str(i),username='user'+str(i)))
    Person.objects.using(db_alias).bulk_create(User_list)

    Task = apps.get_model("taskTracker", "Tasks")
    db_alias=schema_editor.connection.alias
    Task_list=[]
    for i in [6,7,8]:
        Task_list.append(Task(key=str(uuid.uuid4), name='task'+str(i), status='add', parent_id=None, user_id=None))

    Task.objects.using(db_alias).bulk_create(Task_list)

class Migration(migrations.Migration):

    dependencies = [
        ('taskTracker', '0003_auto_20180523_0104'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
